Print the working status of Tag.
F-Army/arduino-dwm1000 pull request #127
Opened 2018-10-24 15:21 UTC by Elon-Wang

Cause my anchor C can't work properly so I add some debug code on tag to see it's working status.

2018-10-24 16:53 UTC, Elon-Wang commented
Fix a bug that caused by sending message to the DW1000 chip too frequently that the chip can't works well and will lost some part of the message

2018-10-24 17:04 UTC, an4cr0n commented on examples/StandardRTLSTag_TWR/StandardRTLSTag_TWR.ino
> +                Serial.println(tempString);
This print statement blocks interrupts when the device could still be receiving messages.

2018-10-24 17:13 UTC, anacromaniac requested changes
Thank you for this fix.
We can probably decrease the delays as probably 25 milliseconds are too much but for now it's fine!
Serial.prints on the opposite can be problematic on slow devices (like arduino 8mhz) we should strive to not use them when they are not safe.
E.g. Prints could cause the opposite of the problem you had, as they block interrupt the device could miss a receive interrupt while printing

2018-10-24 17:17 UTC, an4cr0n commented
oK @Elon-Wang the manual states that at 850kpbs at 256 preamble the transmission time is 380.3us so we can probably get aways with delay(2) rather than delay(25)

2018-10-24 20:13 UTC, Sonic0 commented
Thank you Elon-Wang for the pull request. 
I confirm that the transmission time is 380.3uS for that configuration.
Since only one transmission is allowed in 1mS when using smart power tx, theoretically 700 uS is enough for the delay. In Arduino case, 1mS in perfect in my opinion.

2018-10-24 20:57 UTC, an4cr0n commented
We just need to test it, 1ms seems fine to me too

2018-10-25 15:37 UTC, Elon-Wang commented
Yes, it seems like 1ms works out so, delay(1) is good enough to the system.

2018-10-26 07:50 UTC, anacromaniac approved these changes

2018-10-26 07:54 UTC, an4cr0n commented
Thanks i'm merging

2018-10-26 07:55 UTC, merged